### ISSUE TITLE
VcrClient exposes internal too much

### ISSUE THREAD

**Issue by exoego** [reibitto/be-kind-rewind#10]
I felt that using instance of `VcrClient` is a little annoying, because Intellij IDEA suggest their internal members on code completion.
I think all members of `VcrClient` should be `protected`, so client users does not accidentally touch `VcrClient` members.

**Comment by reibitto** [comment]
Yeah, I agree. That makes sense. I don't think I've added a single visibility modifier in this project yet 😅 But yes, it's something that needs to be done before the first release.
